[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_FONT_GOOGLE_MOCKED_ITERATIONS = "1"
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = [
    ".prisma/client/**/*",
    "node_modules/@prisma/client/**/*",
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"